EXTENSION   = pgtoon
EXTVERSION  = $(shell grep default_version $(EXTENSION).control | sed -e "s/default_version[[:space:]]*=[[:space:]]*'\([^']*\)'/\1/")

# Canonical source contains @extschema@ markers, substituted at
# CREATE EXTENSION time (filesystem or pg_tle). For a standalone psql
# install, `make local` produces a concrete-schema build.
SRC         = $(EXTENSION)--$(EXTVERSION).sql

# Schema used by `make local` (the standalone, non-extension build).
SCHEMA     ?= toon

.PHONY: tle local clean help

# Default target: build the pg_tle installable script.
tle: .pgtle-$(EXTENSION).sql

# Generate the pg_tle install script (wraps SRC in pgtle.install_extension).
# @extschema@ is preserved and substituted by pg_tle at CREATE EXTENSION time.
.pgtle-$(EXTENSION).sql: $(SRC) $(EXTENSION).control create_pgtle_scripts.sh
	EXTENSION='$(EXTENSION)' ./create_pgtle_scripts.sh $(SRC)
	@echo "Built $@ — load with: psql -f $@  then  CREATE EXTENSION $(EXTENSION);"

# Generate a standalone install script for a plain postgres server.
# Substitutes @extschema@ with $(SCHEMA) and creates objects in that schema.
local: $(EXTENSION)-local.sql

$(EXTENSION)-local.sql: $(SRC)
	@( echo "-- pgtoon standalone install (schema: $(SCHEMA))"; \
	   echo "-- Generated by 'make local SCHEMA=$(SCHEMA)' — do not edit."; \
	   echo "CREATE SCHEMA IF NOT EXISTS $(SCHEMA);"; \
	   echo "SET search_path = $(SCHEMA), pg_catalog, pg_temp;"; \
	   echo ""; \
	   sed 's/@extschema@/$(SCHEMA)/g' $(SRC) ) > $@
	@echo "Built $@ — load with: psql -f $@"

clean:
	rm -f .pgtle-$(EXTENSION).sql $(EXTENSION)-local.sql

help:
	@echo "Targets:"
	@echo "  make tle     - build pg_tle install script (.pgtle-$(EXTENSION).sql) [default]"
	@echo "  make local   - build standalone script ($(EXTENSION)-local.sql), SCHEMA=$(SCHEMA)"
	@echo "  make clean   - remove generated files"
